<?php // this is an autogenerated file - do not edit (created Mon, 15 Aug 2011 12:25:38 +0200)
spl_autoload_register(
   function($class) {
      static $classes = null;
      if ($classes === null) {
         $classes = array(
            'foodalizr\\controller\\indexcontroller' => '/controller/IndexController.php',
            'foodalizr\\controller\\apicontroller' => '/controller/ApiController.php',
            'foodalizr\\controller\\mealcontroller' => '/controller/MealController.php',
            'foodalizr\\controller\\personcontroller' => '/controller/PersonController.php',
            'foodalizr\\mapper\\personmapper' => '/mapper/PersonMapper.php',
            'foodalizr\\model\\contribution' => '/model/Contribution.php',
            'foodalizr\\model\\meal' => '/model/Meal.php',
            'foodalizr\\model\\participation' => '/model/Participation.php',
            'foodalizr\\model\\person' => '/model/Person.php',
            'foodalizr\\model\\spending' => '/model/Spending.php',
            'knid\\controller' => '/framework/Knid/Controller.php',
            'knid\\controller\\factory' => '/framework/Knid/Controller/Factory.php',
            'knid\\controller\\front' => '/framework/Knid/Controller/Front.php',
            'knid\\helper\\content\\type\\factory' => '/framework/Knid/Helper/Content/Type/Factory.php',
            'knid\\http\\header' => '/framework/Knid/Http/Header.php',
            'knid\\http\\request' => '/framework/Knid/Http/Request.php',
            'knid\\http\\response' => '/framework/Knid/Http/Response.php',
            'knid\\io\\exception' => '/framework/Knid/Io/Exception.php',
            'knid\\io\\file' => '/framework/Knid/Io/File.php',
            'knid\\json\\model' => '/framework/Knid/Json/Model.php',
            'knid\\mapper' => '/framework/Knid/Mapper.php',
            'knid\\mapper\\exception' => '/framework/Knid/Mapper/Exception.php',
            'knid\\mapper\\factory' => '/framework/Knid/Mapper/Factory.php',
            'knid\\math\\decimal' => '/framework/Knid/Math/Decimal.php',
            'knid\\routing\\exception' => '/framework/Knid/Routing/Exception.php',
            'knid\\routing\\route' => '/framework/Knid/Routing/Route.php',
            'knid\\routing\\router' => '/framework/Knid/Routing/Router.php',
            'knid\\view' => '/framework/Knid/View.php',
            'knid\\view\\factory' => '/framework/Knid/View/Factory.php',
            'knid\\view\\template' => '/framework/Knid/View/Template.php'
          );
      }
      $cn = strtolower($class);
      if (isset($classes[$cn])) {
         require __DIR__ . $classes[$cn];
      }
   }
);
